function Format-MuxxMdCell {
    param([string]$Value)
    if ([string]::IsNullOrEmpty($Value)) { return "" }
    return ($Value -replace '\|', '\|').Trim()
}

function Invoke-MuxxDoc {
    param([string]$OutputPath = "")

    if (-not $OutputPath) {
        $OutputPath = Join-Path (Get-Location) "muxx-environment.md"
    }

    Write-Host ""
    Write-Host "Generating environment report..." -ForegroundColor DarkGray
    Write-Host ""

    $sys     = Get-MuxxSystemSummary
    $tools   = @(Get-MuxxToolRegistry)
    $results = Invoke-MuxxToolCheck -Tools $tools -ResolveVersion -ShowProgress -TimeoutSeconds 4

    $date = Get-Date -Format "yyyy-MM-dd HH:mm"
    $sb   = [System.Text.StringBuilder]::new()

    $winTitle = Format-MuxxMdCell $sys.Windows

    [void]$sb.AppendLine("# Environment Report")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("Generated: $date | MUXX-CLI v$($script:MuxxVersion) | $winTitle")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("## System")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("| | |")
    [void]$sb.AppendLine("|---|---|")
    [void]$sb.AppendLine("| CPU | $(Format-MuxxMdCell $sys.CPU) |")
    [void]$sb.AppendLine("| Memory | $(Format-MuxxMdCell $sys.Memory) |")
    [void]$sb.AppendLine("| Uptime | $(Format-MuxxMdCell $sys.Uptime) |")
    [void]$sb.AppendLine("| Host | $(Format-MuxxMdCell $sys.Host) |")
    [void]$sb.AppendLine("| User | $(Format-MuxxMdCell $sys.User) |")
    [void]$sb.AppendLine("| PowerShell | v$(Format-MuxxMdCell $sys.PowerShell) |")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("## Tools")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("| Tool | Status | Version |")
    [void]$sb.AppendLine("|------|:------:|---------|")

    foreach ($r in $results) {
        $status = switch ($r.Status) {
            "Installed"    { "Installed" }
            "NotInstalled" { "Not installed" }
            default        { "Warning" }
        }
        $version = if ($r.Version) { $r.Version } else { "-" }
        $nameCell    = Format-MuxxMdCell $r.Name
        $statusCell  = Format-MuxxMdCell $status
        $versionCell = Format-MuxxMdCell $version
        [void]$sb.AppendLine("| $nameCell | $statusCell | $versionCell |")
    }

    $ok    = @($results | Where-Object Status -eq "Installed").Count
    $total = $results.Count
    $score = if ($total) { [math]::Round(($ok / $total) * 100) } else { 0 }

    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("**Score: $ok / $total ($score%)**")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("---")
    [void]$sb.AppendLine("_Generated by [MUXX-CLI](https://github.com/JoshDebris/muxx-cli)_")

    $content = $sb.ToString()
    [System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.Encoding]::UTF8)

    Write-Host ""
    Write-Host "muxx-environment.md" -ForegroundColor Cyan -NoNewline
    Write-Host " written." -ForegroundColor Green
    Write-Host $OutputPath -ForegroundColor DarkGray
}
